---
#
# https://gist.github.com/niro1987/e7be4b6173d819af3b55f1d4ec114df4
#
id: slaapkamer-ikea_remote
alias: Slaapkamer IKEA Remote
description: >-
  Zet alle verlichting uit met de druk van elke knop op de IKEA Remote.

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: 5279ce03243d54e6596565d4af4d3567

action:
  - choose:
      # Short-Press on the power button.
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.event.data.command == "toggle" }}
        sequence:
          - service: automation.trigger
            entity_id: automation.slaapkamer_schakelaar

      # Long-Press on the power button.
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.event.data.command == "move_to_level_with_on_off" }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.slaapkamer
            data:
              brightness: 254
              hs_color:
                - 38.222
                - 52.941

      # Short-Press on the dim-up button.
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.event.data.command == "step_with_on_off" }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >-
                      {{
                        expand(state_attr('light.slaapkamer', 'entity_id'))
                          |selectattr('state', 'eq', 'on')
                          |map(attribute='entity_id')
                          |list
                          |count
                        > 0
                      }}
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: >-
                        {{
                          expand(state_attr('light.slaapkamer', 'entity_id'))
                          |selectattr('state', 'eq', 'on')
                          |map(attribute='entity_id')
                          |list
                        }}
                    data:
                      brightness_step_pct: 10
            default:
              - choose:
                  - conditions:
                      - condition: time
                        before: "10:00"
                        after: "21:00"
                    sequence:
                      - service: light.turn_on
                        target:
                          entity_id: light.bed
                        data:
                          brightness_step_pct: 10
                default:
                  - service: light.turn_on
                    target:
                      entity_id: light.slaapkamer
                    data:
                      brightness_step_pct: 10

      # # Long-Press on the dim-up button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "move_with_on_off" }}'
        sequence:
          - repeat:
              while: []
              sequence:
                - choose:
                    - conditions:
                        - condition: template
                          value_template: >-
                            {{
                              expand(state_attr('light.slaapkamer', 'entity_id'))
                                |selectattr('state', 'eq', 'on')
                                |map(attribute='entity_id')
                                |list
                                |count
                              > 0
                            }}
                      sequence:
                        - service: light.turn_on
                          target:
                            entity_id: >-
                              {{
                                expand(state_attr('light.slaapkamer', 'entity_id'))
                                |selectattr('state', 'eq', 'on')
                                |map(attribute='entity_id')
                                |list
                              }}
                          data:
                            brightness_step_pct: 10
                            transition: 0.5
                  default:
                    - choose:
                        - conditions:
                            - condition: time
                              before: "10:00"
                              after: "21:00"
                          sequence:
                            - service: light.turn_on
                              target:
                                entity_id: light.bed
                              data:
                                brightness_step_pct: 10
                                transition: 0.5
                      default:
                        - service: light.turn_on
                          target:
                            entity_id: light.slaapkamer
                          data:
                            brightness_step_pct: 10
                            transition: 0.5
                - delay:
                    milliseconds: 500

      # # Short-Press on the dim-down button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "step" }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: >-
                {{
                  expand(state_attr('light.slaapkamer', 'entity_id'))
                  |map(attribute='entity_id')
                  |list
                }}
            data:
              brightness_step_pct: -10

      # # Long-Press on the dim-down button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "move" }}'
        sequence:
          - repeat:
              while: []
              sequence:
                - choose:
                    - conditions:
                        - condition: template
                          value_template: >-
                            {{
                              expand(state_attr('light.slaapkamer', 'entity_id'))
                                |selectattr('state', 'eq', 'on')
                                |map(attribute='entity_id')
                                |list
                                |count
                              > 0
                            }}
                      sequence:
                        - service: light.turn_on
                          target:
                            entity_id: >-
                              {{
                                expand(state_attr('light.slaapkamer', 'entity_id'))
                                |selectattr('state', 'eq', 'on')
                                |map(attribute='entity_id')
                                |list
                              }}
                          data:
                            brightness_step_pct: -10
                            transition: 0.5
                  default:
                    - choose:
                        - conditions:
                            - condition: time
                              before: "10:00"
                              after: "21:00"
                          sequence:
                            - service: light.turn_on
                              target:
                                entity_id: light.bed
                              data:
                                brightness_step_pct: -10
                                transition: 0.5
                      default:
                        - service: light.turn_on
                          target:
                            entity_id: light.slaapkamer
                          data:
                            brightness_step_pct: -10
                            transition: 0.5
                - delay:
                    milliseconds: 500

      # # Short-Press on the color-up button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "press" }}'
          - condition: template
            value_template: "{{ trigger.event.data.args == [256,13,0] }}"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: media_player.slaapkamer_mini
                    state: playing
                sequence:
                  - service: media_player.media_next_track
                    target:
                      entity_id: media_player.slaapkamer_mini
            default:
              - service: light.turn_on
                target:
                  entity_id: light.bed
                data:
                  brightness: 100
                  color_name: red

      # # Long-Press on the color-up button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "hold" }}'
          - condition: template
            value_template: "{{ trigger.event.data.args == [3328,0] }}"
        sequence:
          - service: media_player.turn_off
            target:
              entity_id: media_player.slaapkamer_mini

      # # Short-Press on the color-down button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "press" }}'
          - condition: template
            value_template: "{{ trigger.event.data.args == [257,13,0] }}"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: media_player.slaapkamer_mini
                    state: playing
                sequence:
                  - service: media_player.media_previous_track
                    target:
                      entity_id: media_player.slaapkamer_mini
            default:
              - service: light.turn_on
                target:
                  entity_id: light.bed
                data:
                  brightness: 100
                  color_name: red

      # # Long-Press on the color-down button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "hold" }}'
          - condition: template
            value_template: "{{ trigger.event.data.args == [3329,0] }}"
        sequence:
          - service: media_player.turn_off
            target:
              entity_id: media_player.slaapkamer_mini

    # Any other event will cancel the repeat loops.
    default: []
