---
esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini_pro

binary_sensor:
  - platform: status
    name: "${devicename} Status"

sensor:
  - platform: wifi_signal
    id: "wifisignal"
    update_interval: 60s
    name: "${devicename} Signal"

switch:
  - platform: restart
    name: "${devicename} Reboot"
    id: "reboot"
