---
esphome:
  name: ${devicename}
  platform: ESP32
  board: esp32doit-devkit-v1

binary_sensor:
  - platform: status
    name: "${devicename} Status"

sensor:
  - platform: wifi_signal
    id: "wifisignal"
    update_interval: 60s
    name: "${devicename} Signal"

switch:
  - platform: restart
    id: restrt
    name: "${devicename} Restart"
  - platform: safe_mode
    name: "${devicename} Restart (Safe Mode)"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${devicename} IP"
    mac_address:
      name: "${devicename} MAC"
