---
#
#
#
id: overloop-flux
alias: Overloop Flux
description: >-
  Zet de flux functie uit wanneer het licht uit wordt gezet.

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: light.overloop
    from: "on"
    to: "off"

action:
  - service: switch.turn_off
    data:
      entity_id: switch.flux_overloop
