---
#
#
#
id: alarm_armed_home
alias: Alarm Armed Home
description: Alarm armed on Home mode.

mode: queued
max: 1
max_exceeded: silent

trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm
    to: armed_home

action:
  - service: notify.mobile_app_nimbus_2000
    data:
      message: "Armed Home"
      title: "Alarm"
