id: alarm-voordeur_tag
alias: Voordeur NFC Tag
description: >-
  Open voordeur zodra NFC tag wordt gescand.

mode: single

trigger:
  - platform: tag
    tag_id: ef228741-9c01-4742-9460-22eac6841a4f

action:
  - service: lock.unlock
    target:
      entity_id: lock.voordeur
