- id: '1605803083165'
  alias: Eettafel Helper On
  description: ''
  trigger:
  - platform: state
    entity_id: light.eettafel
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.eettafel
  mode: single
- id: '1605803127020'
  alias: Eettafel Helper Off
  description: ''
  trigger:
  - platform: state
    entity_id: light.eettafel
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.eettafel
  mode: single
- id: '1605803244162'
  alias: Eettafel Unavailable Fix
  description: ''
  trigger:
  - platform: state
    entity_id: light.eettafel
    from: unavailable
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.eettafel
    state: 'on'
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.eettafel
  mode: single
