- id: '1697730194588'
  alias: Flash Light 1
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.philips_929003045201_01_light
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data:
      flash: long
    target:
      entity_id: light.philips_929003045201_01_light
  - service: notify.mobile_app_nimbus_2000
    data:
      message: Flash Light 1
  mode: single
- id: '1697730254415'
  alias: Flash Light 2
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.philips_929003045201_03_light
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data:
      flash: long
    target:
      entity_id: light.philips_929003045201_03_light
  - service: notify.mobile_app_nimbus_2000
    data:
      message: Flash Light 2
  mode: single
