---
#
#
#
id: eetkamer-eettafel_uitval_fix
alias: Eetkamer Eettafel Uitval Fix
description: >-
  Zet de Eettafel verlichting weer aan nadat deze is uitgevallen.

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: light.eettafel

action:
  - choose:
      # Zet Eettafel aan na uitval indien helper aan staat.
      - conditions:
          - condition: template
            value_template: "{{ trigger.from_state.state == 'unavailable' }}"
          - condition: template
            value_template: "{{ trigger.to_state.state == 'off' }}"
          - condition: state
            entity_id: input_boolean.eettafel
            state: "on"
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.eettafel
      # Zet helper aan bij normaal inschakelen Eettafel.
      - conditions:
          - condition: template
            value_template: "{{ trigger.from_state.state == 'off' }}"
          - condition: template
            value_template: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.eettafel
      # Zet helper uit bij normaal uitschakelen Eettafel.
      - conditions:
          - condition: template
            value_template: "{{ trigger.from_state.state == 'on' }}"
          - condition: template
            value_template: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.eettafel
