---
#
id: eetkamer-stekkerblok
alias: Stekkerblok
description: Zet het stekkerblok aan en uit

mode: single
max_exceeded: silent

variables:
  future_state: "on"

trigger:
  - platform: time
    at: "00:00:00"
    id: "off"
  - platform: time
    at: "06:00:00"
    id: "on"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: " off"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.stekkerblok
    default:
      - service: switch.turn_on
        target:
          entity_id: switch.stekkerblok
