---
#
#
#
id: 'staircase-light'
alias: Trapverlichting
description: 'Verlichting op de trap aan bij beweging'
mode: restart
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - binary_sensor.trap
action:
  - choose:
    - conditions:
        - condition: state
          entity_id: binary_sensor.trap
          state: 'on'
        # - condition: template
        #   value_template: '{{ state_attr("sun.sun", "elevation") < -6 }}'
      sequence:
        - service: light.turn_on
          data_template:
            entity_id: light.trap
            # brightness: 50
            # hs_color:
            #   - 15
            #   - 71
            # transition: 1
    default:
      - service: light.turn_off
        data_template:
          entity_id: light.trap
          transition: 1