---
#
#
#
id: staircase-light
alias: Trapverlichting
description: Verlichting op de trap aan bij beweging.

mode: restart

trigger:
  - platform: state
    entity_id:
      - binary_sensor.trap

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.trap
          - delay: "00:03:30"
          - service: light.turn_off
            data:
              entity_id: light.trap
    default:
      - service: light.turn_off
        data:
          entity_id: light.trap
