---
#
#
#
id: slaapkamer-ikea_shortcut
alias: Slaapkamer IKEA Shortcut
description: >-
  Zet alle verlichting uit met de druk van elke knop op de IKEA Remote.

mode: single
max_exceeded: silent

variables:
  entities:
    - light.slaapkamer_plafond
    - light.slaapkamer_niels
    - light.slaapkamer_danielle
    - light.badkamer_plafond
    - light.badkamer_spiegel
    - light.overloop
    - light.trap
    - light.gang
    - light.lily_plafond
    - light.olivia_plafond
    - light.zolder

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: 14a2ef3dbbd93a415abb3b8df25b1bad
      command: "on"

action:
  - service: light.turn_off
    target:
      entity_id: "{{ entities }}"
  - delay:
      milliseconds: 200
