---
#
#
#
id: toilet-light
alias: Toiletverlichting
description: Verlichting in het toilet aan bij beweging.

mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.toilet
    from: "off"
    to: "on"
    for: "00:00:01"
  - platform: state
    entity_id: binary_sensor.toilet
    from: "on"
    to: "off"
    for: "00:15:00"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.toilet
          - delay: "00:15:00"
          - service: light.turn_off
            data:
              entity_id: light.toilet
    default:
      - service: light.turn_off
        data:
          entity_id: light.toilet
