---
#

blueprint:
  source_url: https://github.com/niro1987/homeassistant-config/blob/main/blueprints/automation/niro1987/lights_off_no_motion.yaml

  name: Turn off lights on no motion

  description: >-
    This automation turns off the lights after a certain period of motion inactivity.

  domain: automation

  input:
    lights:
      name: Lights
      description: The lights that you want to turn off
      selector:
        target:
          entity:
            domain: light
    motion:
      name: Motion
      description: The motion sensor to measure inactivity.
      selector:
        entity:
          device_class: motion
    inactivity:
      name: Inactivity
      description: The time in minutes of inactivity required before the lights are turned off.
      selector:
        number:
          min: 0
          max: 720
          step: 1
          unit_of_measurement: minutes
          mode: box

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion
    to: "off"
    for:
      minutes: !input inactivity

action:
  - service: light.turn_off
    target: !input lights
