---
# This automation simulates the use of the IKEA TRADFRI Dimmer control
# connected through ZHA.

blueprint:
  source_url: https://github.com/niro1987/homeassistant-config/blob/main/blueprints/automation/niro1987/zha_ikea_tradfri_1button_remote_scene.yaml

  name: ZHA - IKEA TRADFRI - 1 Button Remote - Scenes

  description: >-
    This automation simulates the use of the IKEA TRADFRI SHORTCUT Button
    connected through ZHA.

  domain: automation

  input:
    remote:
      name: IKEA TRADFRI remote control
      description: Select the remote control you wish to use.
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: TRADFRI SHORTCUT Button
    scene_short:
      name: Short Press Scene
      description: Select the scene to be activated with a short press.
      selector:
        entity:
          domain: scene
    scene_long:
      name: Long Press Scene
      description: Select the scene to be activated with a long press.
      selector:
        entity:
          domain: scene

mode: single
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - choose:
      # Short-Press
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "on" }}'
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input scene_short
          - delay:
              milliseconds: 500

      # Long-Press
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "move_with_on_off" }}'
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input scene_long
          - delay:
              milliseconds: 500

    # Any other event will cancel the repeat loops (i.e. releasing the [on|off] button)
    default: []
