---
# This automation simulates the use of the IKEA TRADFRI Dimmer control
# connected through ZHA.

# | Button      | Action               |
# | ----------- | -------------------- |
# | on (short)  | Turn the light on    |
# | off (short) | Turn the light off   |
# | on (long)   | Increase temperature |
# | off (long)  | Decrease temperature |

blueprint:
  source_url: https://github.com/niro1987/homeassistant-config/blob/master/blueprints/automation/niro1987/zha_ikea_tradfri_2button_remote_temperature.yaml

  name: ZHA - IKEA TRADFRI - 2 Button Remote - OnOff and Temperature

  description: >-
    This automation simulates the use of the IKEA TRADFRI Dimmer
    connected through ZHA.

  domain: automation

  input:
    remote_ieee:
      name: Remote IEEE
      description: Lookup on the device page.
      selector:
        text:
          multiline: false
      default: 01:a2:34:bc:de:56:7f:89
    light_entity:
      name: Light
      description: The light entity to control.
      selector:
        entity:
          domain: light
      default: light.living_room

mode: restart
max_exceeded: silent

variables:
  var_remote_ieee: !input remote_ieee
  var_light_entity: !input light_entity

trigger:
  - platform: event
    event_type: zha_event

condition:
  - condition: template
    value_template: "{{ trigger.event.data.device_ieee == var_remote_ieee }}"

action:
  - choose:
      # Short-Press the on button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "on" }}'
        sequence:
          - service: light.turn_on
            data:
              entity_id: !input light_entity
              hs_color:
                - 38.222
                - 52.941
              transition: 1
      # Short-Press the off button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "off" }}'
        sequence:
          - service: light.turn_off
            data:
              entity_id: !input light_entity
              transition: 1
      # Long-Press the on button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "move_with_on_off" }}'
        sequence:
          - repeat:
              while: []
              sequence:
                - service: light.turn_on
                  data:
                    entity_id: !input light_entity
                    color_temp: >-
                      {% if state_attr(var_light_entity, "color_temp") + 18 > 500 %}
                        {{ 500 }}
                      {% else %}
                        {{ state_attr(var_light_entity, "color_temp") + 18 }}
                      {% endif %}
                    transition: 0.5
                - delay:
                    milliseconds: 500
      # Long-Press the off button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "move" }}'
        sequence:
          - repeat:
              while: []
              sequence:
                - service: light.turn_on
                  data:
                    entity_id: !input light_entity
                    color_temp: >-
                      {% if state_attr(var_light_entity, "color_temp") - 18 < 153 %}
                        {{ 153 }}
                      {% else %}
                        {{ state_attr(var_light_entity, "color_temp") - 18 }}
                      {% endif %}
                    transition: 0.5
                - delay:
                    milliseconds: 500
    # Any other event will cancel the repeat loops (i.e. releasing the [on|off] button)
    default: []
