id: telegram-alarm_away
alias: Telegram Alarm Away
description: Ask to turn the alarm on when everyone is away.

mode: single
max_exceeded: silent

variables:
  telegram_target: !secret telegram_groupchat

trigger:
  - platform: numeric_state
    entity_id: zone.home
    below: 1
    # for:
    #   minutes: 15

condition:
  - condition: state
    entity_id: alarm_control_panel.verisure_alarm
    state: "disarmed"

action:
  - service: telegram_bot.send_message
    data:
      target: "{{telegram_target}}"
      title: "*Alarm*"
      message: >-
        Zo te zien is er niemand thuis,
        wil je dat ik het alarm inschakel?
      inline_keyboard:
        - "Ja! Volledig:/telegram-alarm_away_away, Ja! Gedeeltelijk:/telegram-alarm_away_home"
        - "Nee:/telegram-alarm_away_no"

  - wait_for_trigger:
      - platform: event
        event_type: "telegram_callback"
        event_data:
          command:
            - "/telegram-alarm_away_away"
            - "/telegram-alarm_away_home"
            - "/telegram-alarm_away_no"
    timeout:
      minutes: 30
    continue_on_timeout: true

  - service: telegram_bot.edit_replymarkup
    data:
      chat_id: "{{telegram_target}}"
      message_id: "last"
      inline_keyboard: []

  - choose:
      - conditions: >-
          {{wait.trigger.event.data.command == '/telegram-alarm_away_away'}}
        sequence:
          - service: alarm_control_panel.alarm_arm_away
            target:
              entity_id: alarm_control_panel.verisure_alarm
            data:
              code: !secret verisure_alarm_code

          - service: telegram_bot.send_message
            data:
              target: "{{telegram_target}}"
              title: "*Alarm*"
              message: "Het alarm is ingeschakeld."

      - conditions: >-
          {{wait.trigger.event.data.command == '/telegram-alarm_away_home'}}
        sequence:
          - service: alarm_control_panel.alarm_arm_home
            target:
              entity_id: alarm_control_panel.verisure_alarm
            data:
              code: !secret verisure_alarm_code

          - service: telegram_bot.send_message
            data:
              target: "{{telegram_target}}"
              title: "*Alarm*"
              message: "Het alarm is ingeschakeld."

      - conditions: >-
          {{wait.trigger.event.data.command == '/telegram-alarm_away_no'}}
        sequence:
          - service: telegram_bot.send_message
            data:
              target: "{{telegram_target}}"
              title: "*Alarm*"
              message: "Nee? Oké."

    default:
      - service: telegram_bot.send_message
        data:
          target: "{{telegram_target}}"
          title: "*Alarm*"
          message: >-
            Verlopen - Open de Verisure app om het alarm in te schakelen.
