---
#
# Notify anyone who is home that the tumble dryer is ready
# Power-cycle the dryer to stop it from spinning,
# the damn thing has a so called 'keep-soft' feature..
#
id: telegram-dryer
alias: Dryer Notification
description: Send a notification when the dryer is ready

mode: single
max_exceeded: silent

variables:
  telegram_target: !secret telegram_groupchat

trigger:
  - platform: state
    entity_id: binary_sensor.droger
    from: "on"
    to: "off"

condition:
  - condition: state
    entity_id: switch.droger
    state: "on"

action:
  - service: telegram_bot.send_message
    data:
      target: "{{telegram_target}}"
      title: "*Droger*"
      message: "De droger is klaar."
  - service: switch.turn_off
    entity_id:
      - switch.droger
  - delay:
      seconds: 1
  - service: switch.turn_on
    entity_id:
      - switch.droger
