---
#
# Send notification when FysioBO computers are offline
#
id: telegram-ha_boot
alias: Telegram Home Assitant Boot Notification
description: Send a notification when Home Assistant reboots

mode: single
max_exceeded: silent

variables:
  telegram_target: !secret telegram_groupchat

trigger:
  - platform: homeassistant
    event: start

action:
  - service: telegram_bot.send_message
    data:
      target: "{{telegram_target}}"
      title: "*Home Assistant*"
      message: "Home Assistant is (opnieuw) opgestart."
