---
id: telegram-hvc
alias: Telegram HVC Notification
description: Send a notification when there is a garbage collection

mode: single
max_exceeded: silent

variables:
  telegram_target: !secret telegram_groupchat

trigger:
  - platform: time
    at: "19:00:00"

condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.hvc_restafval
        attribute: day
        state: Morgen
      - condition: state
        entity_id: sensor.hvc_gft
        attribute: day
        state: Morgen
      - condition: state
        entity_id: sensor.hvc_plastic
        attribute: day
        state: Morgen
      - condition: state
        entity_id: sensor.hvc_papier
        attribute: day
        state: Morgen

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: sensor.hvc_restafval
            attribute: day
            state: Morgen
        sequence:
          - service: telegram_bot.send_message
            data:
              target: "{{telegram_target}}"
              title: "*HVC*"
              message: >
                "Morgen komt Restafval, vergeet de bak niet aan de weg te zetten!"
      - conditions:
          - condition: state
            entity_id: sensor.hvc_gft
            attribute: day
            state: Morgen
        sequence:
          - service: telegram_bot.send_message
            data:
              target: "{{telegram_target}}"
              title: "*HVC*"
              message: >
                "Morgen komt GFT, vergeet de bak niet aan de weg te zetten!"
      - conditions:
          - condition: state
            entity_id: sensor.hvc_plastic
            attribute: day
            state: Morgen
        sequence:
          - service: telegram_bot.send_message
            data:
              target: "{{telegram_target}}"
              title: "*HVC*"
              message: >
                "Morgen komt Plastic, vergeet de bak niet aan de weg te zetten!"
      - conditions:
          - condition: state
            entity_id: sensor.hvc_papier
            attribute: day
            state: Morgen
        sequence:
          - service: telegram_bot.send_message
            data:
              target: "{{telegram_target}}"
              title: "*HVC*"
              message: >
                "Morgen komt Oud Papier, vergeet het niet aan de weg te zetten!"
