---
#
# Notify anyone who is home that the waching machine is ready.
#
id: telegram-washingmachine
alias: Washing Machine Notification
description: Send a notification when the washing machine is ready

mode: single
max_exceeded: silent

variables:
  telegram_target: !secret telegram_groupchat

trigger:
  - platform: state
    entity_id: binary_sensor.wasmachine
    from: "on"
    to: "off"

condition:
  - condition: state
    entity_id: switch.wasmachine
    state: "on"

action:
  - service: telegram_bot.send_message
    data:
      target: "{{telegram_target}}"
      title: "*Wasmachine*"
      message: "De wasmachine is klaar."
