---
#
id: niels-pillen
alias: Niels Pillen Herinnering
description: Stuur een herinnering om 21:00 om pillen in te nemen

mode: restart

triggers:
  - trigger: time
    at: "21:00:00"

actions:
  - alias: Turn on helper
    action: input_boolean.turn_on
    target:
      entity_id:
        - input_boolean.niels_pillen

  - alias: Repeat every 10 minutes
    repeat:
      while:
        - alias: Helper is On
          condition: state
          entity_id: input_boolean.niels_pillen
          state: "on"
      sequence:
        - alias: Send actionable notification
          action: notify.mobile_app_nimbus_2000
          data:
            title: Pillen
            message: Het is tijd om je pilletje in te nemen
            data:
              url: /lovelace/pillen
              push:
                sound:
                  name: Alert_Health_Haptic.caf
                  critical: 1
                  volume: 1
              actions:
                - action: PILLS_DONE
                  title: Ingenomen
                  authenticationRequired: true
                  icon: sfsymbols:pill
        - alias: Wait for confirmation
          wait_for_trigger:
            - alias: Confirmation given
              trigger: event
              event_type: mobile_app_notification_action
              event_data:
                action: PILLS_DONE
            - alias: Helper turned Off
              trigger: state
              entity_id:
                - input_boolean.niels_pillen
              to: "off"
          timeout:
            minutes: 10
        - alias: Turn off helper on confirmation
          if:
            - alias: Confirmation is given
              condition: template
              value_template: "{{ wait.trigger.event.data.action == 'PILLS_DONE' }}"
          then:
            - alias: Turn helper Off
              action: input_boolean.turn_off
              target:
                entity_id: input_boolean.niels_pillen
