---
#
# Ì've modified my existing Busch-Jaeger light switch with ESPHome and a Sonoff Mini
# to make sure I can still toggle the hue light when the switch is in the off position.
#
id: landing_first-switch
alias: Schakelaar Overloop
description: Bedient de verlichting.

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: binary_sensor.overloop_switch
    from: "on"
    to: "off"
  - platform: state
    entity_id: binary_sensor.overloop_switch
    from: "off"
    to: "on"

action:
  - service: light.toggle
    entity_id: light.overloop
    data:
      brightness: 254
