---
#
#
#
id: '1594645738949'
alias: Slaapkamer Lily Overdag Notificatie Niels
description: ''
trigger:
  - platform: state
    entity_id: light.lily_plafond
    from: 'off'
    to: 'on'
    for:
      minutes: 5
condition:
  - condition: state
    entity_id: sun.sun
    state: above_horizon
  - condition: time
    after: '09:00:00'
    before: '20:00:00'
action:
  - service: camera.snapshot
    data_template:
      entity_id: camera.foscam_lily
      filename: '/config/www/snapshots/current.foscam_lily.jpg'
  - delay:
      seconds: 2
  - service: notify.mobile_app_nimbus_2000
    data:
      title: Lily
      message: Lily d'r licht staat aan.
      data:
        apns_headers:
          apns-collapse-id: Energie
        push:
          thread-id: lily_plafond
        attachment:
          url: '/local/snapshots/current.foscam_lily.jpg'
        url: '/lovelace/slaapkamer_lily'
      
      
    