---
#
#
#
id: '1594827852053'
alias: Slaapkamer Lily Overdag Notificatie Daan
description: ''
trigger:
  - platform: state
    entity_id: light.lily_plafond
    from: 'off'
    to: 'on'
    for:
      minutes: 5
condition:
  - condition: state
    entity_id: sun.sun
    state: above_horizon
  - condition: time
    after: '09:00:00'
    before: '20:00:00'
action:
  - service: camera.snapshot
    data_template:
      entity_id: camera.foscam_lily
      filename: '/config/www/snapshots/current.foscam_lily.jpg'
  - delay:
      seconds: 2
  - service: notify.mobile_app_j9210
    data:
      title: Lily
      message: Lily d'r licht staat aan.
      data:
        group: Energie
        tag: lily_plafond
        image: '/local/snapshots/current.foscam_lily.jpg'
        clickAction: '/lovelace/slaapkamer_lily'
        timeout: 600