---
#
#
#
id: '1594803316444'
alias: Verlichting Uitschakelen adhv iOS Notificatie
description: ''
trigger:
- event_data:
    actionName: TURN_OFF
    categoryName: light_off
  event_type: ios.notification_action_fired
  platform: event
condition:
- condition: template
  value_template: '{{ states(trigger.event.data.action_data.entity_id) != ''unknown''
    }}'
action:
- data_template:
    entity_id: '{{trigger.event.data.action_data.entity_id}}'
  service: light.turn_off