---
#
# This routine resets the speaker volume for the Google Home Mini
# 
id: 'routines-reset_volume_google_home'
alias: Google Home Mini VOlume
description: 'Herstel het volume van de Google Home'
mode: single
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: time
    at: '08:00:00'
  - platform: time
    at: '21:00:00'
action:
  - choose:
    - conditions:
      - condition: time
        before: '08:00:00'
        after: '21:00:00'
      sequence:
        - service: media_player.volume_set
          data:
            entity_id: 
              - media_player.woonkamer_mini
              - media_player.slaapkamer_mini
            volume_level: 0.1
    default:
      - service: media_player.volume_set
        data:
          entity_id:
            - media_player.woonkamer_mini
            - media_player.slaapkamer_mini
          volume_level: 0.3