---
#
# This routine resets the speaker volume for the Google Home Mini
#
id: routines-reset_volume_google_home
alias: Google Home Mini Volume
description: Herstel volume van de Google Home.

mode: single
max_exceeded: silent

trigger:
  - platform: time
    at: "09:00:00"
  - platform: time
    at: "21:00:00"

action:
  - choose:
      - conditions:
          - condition: time
            before: "09:00:00"
            after: "21:00:00"
        sequence:
          - service: media_player.volume_set
            data:
              entity_id:
                - media_player.woonkamer_mini
                - media_player.slaapkamer_mini
                - media_player.zolder_mini
              volume_level: 0.1
    default:
      - service: media_player.volume_set
        data:
          entity_id:
            - media_player.woonkamer_mini
            - media_player.slaapkamer_mini
            - media_player.zolder_mini
          volume_level: 0.3
