---
#
# This routine turns on the lights in the bathroom as well as the 
# master bedroom when we turn off all the lights on the ground-floor.
#
id: 'routines-to_bed'
alias: Naar bed, Naar bed, Zei Duimelot
description: 'Eerst nog wat eten zei likkepot'
mode: single
trigger:
  - platform: state
    entity_id: light.begane_grond
    from: 'on'
    to: 'off'
condition:
  - condition: time
    before: '01:00:00'
    after: '22:00:00'
  - condition: state
    entity_id: light.eerste_verdieping
    state: 'off'
action:
  - service: light.turn_on
    entity_id: light.badkamer_plafond
    data:
      brightness: 1
  - service: light.turn_on
    entity_id: light.bed
    data:
      brightness: 50
      hs_color:
      - 38.222
      - 52.941