---
#
#
#
id: '1594458559299'
alias: Naar bed routine
description: ''
trigger:
  - platform: state
    entity_id: light.begane_grond
    from: 'on'
    to: 'off'
condition:
  - condition: time
    before: '01:00:00'
    after: '22:00:00'
  - condition: state
    entity_id: light.eerste_verdieping
    state: 'off'
action:
  - service: light.turn_on
    entity_id: light.badkamer_plafond
    data:
      brightness: 1
  - service: light.turn_on
    entity_id: light.bed
    data:
      brightness: 50
      hs_color:
      - 38.222
      - 52.941