---
#
# 
# 
id: '1595190703274'
alias: Woonkamer Mini Volume Laag
description: ''
trigger:
  - platform: time
    at: '21:00:00'
action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.woonkamer_mini
      volume_level: 0.1