---
#
# 
# 
id: '1595190679155'
alias: Woonkamer Mini Volume Hoog
description: ''
trigger:
  - platform: time
    at: '08:00:00'
action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.woonkamer_mini
      volume_level: 0.3