---
# 
# 
# 
esphome_restart:
  name: Esphome Restart
  entities:
    - switch.afzuiging_restart
    - switch.badkamer_restart
    - switch.bar_restart
    - switch.bel_restart
    - switch.eettafel_restart
    - switch.gang_restart
    - switch.keuken_restart
    - switch.slaapkamer_lily_restart
    - switch.slaapkamer_olivia_restart
    - switch.slaapkamer_restart
    - switch.zolder_restart