---
#
#
#
name: ESPHome Signal
entities:
  - sensor.eettafel_signal
  - sensor.bar_signal
  - sensor.keuken_signal
  - sensor.gang_signal
  - sensor.toilet_signal
  - sensor.bel_signal
  - sensor.schuur_signal
  - sensor.overloop_signal
  - sensor.badkamer_signal
  - sensor.slaapkamer_signal
  - sensor.slaapkamer_lily_signal
  - sensor.slaapkamer_olivia_signal
  - sensor.afzuiging_signal
  - sensor.zolder_signal
