---
#
#
#
name: ESPHome Status
entities:
  - binary_sensor.eettafel_status
  - binary_sensor.bar_status
  - binary_sensor.keuken_status
  - binary_sensor.gang_status
  - binary_sensor.toilet_status
  - binary_sensor.bel_status
  - binary_sensor.schuur_status
  - binary_sensor.overloop_status
  - binary_sensor.badkamer_status
  - binary_sensor.slaapkamer_status
  - binary_sensor.slaapkamer_lily_status
  - binary_sensor.slaapkamer_olivia_status
  - binary_sensor.afzuiging_status
  - binary_sensor.zolder_status