---
#
#
#
id: eettafel_helper_on
alias: Eettafel Helper On
description: Turn the helper on when the light is turned on.

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: light.eettafel
    from: "off"
    to: "on"

action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.eettafel
