---
#
# Send notification when FysioBO computers are offline
#
id: system_fysiobo
alias: FysioBO Offline Notification
description: Send a notification when one of the FysioBO computers is offline

mode: parallel
max: 3
max_exceeded: silent

variables:
  name: "Unknown"

trigger:
  - platform: state
    entity_id: binary_sensor.fysiobo1
    from: "on"
    to: "off"
    variables:
      name: FysioBO1
  - platform: state
    entity_id: binary_sensor.fysiobo2
    from: "on"
    to: "off"
    variables:
      name: FysioBO2
  - platform: state
    entity_id: binary_sensor.fysiobo3
    from: "on"
    to: "off"
    variables:
      name: FysioBO3

action:
  - service: notify.mobile_app_nimbus_2000
    data:
      title: "{{name}}"
      message: "{{name}} is offline!"
  - service: notify.mobile_app_j9210
    data:
      title: "{{name}}"
      message: "{{name}} is offline!"
