---
#
# This workaround is needed untill the
# [issue](https://github.com/zigpy/zha-device-handlers/issues/1404)
# is resolved.
id: system_smartplugs
alias: Smartplugs Workaround
description: Workaround to read power measurements from the smartplugs.

mode: restart

trigger:
  - platform: time_pattern
    minutes: "/1"

action:
  - service: zha_toolkit.attr_read
    data:
      ieee: a4:c1:38:a3:53:8f:8b:d4
      cluster: 1794
      attribute: 0
  - service: zha_toolkit.attr_read
    data:
      ieee: a4:c1:38:28:d2:26:34:e9
      cluster: 1794
      attribute: 0
