---
# 
# 
# 
id: "1594194891882"
alias: Badkamer Spiegelverwarming Uit
description: ""
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - sensor.badkamer_luchtvochtigheid_5min
condition:
  - condition: state
    entity_id: switch.badkamer_spiegelverwarming
    state: 'on'
  - condition: template
    value_template: "{{ (state_attr('sensor.badkamer_luchtvochtigheid_5min', 'variance') | float) < 10 }}"
action:
  - service: switch.turn_off
    data:
      entity_id:
        - switch.badkamer_spiegelverwarming