---
#
#
#
id: '1594194765644'
alias: Badkamer Spiegelverwarming Aan
description: ''
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - sensor.badkamer_luchtvochtigheid_5min
condition:
  - condition: state
    entity_id: switch.badkamer_spiegelverwarming
    state: 'off'
  - condtion: numeric_state
    entity_id: sensor.badkamer_luchtvochtigheid_5min_variance
    above: 10
action:
  - service: switch.turn_on
    data:
      entity_id: 
        - switch.badkamer_spiegelverwarming