---
# 
# 
# 
id: "1594194891882"
alias: Badkamer Spiegelverwarming Uit
description: ""
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - sensor.badkamer_luchtvochtigheid_5min
      - light.badkamer
      - fan.afzuiging
condition:
  - condition: state
    entity_id: switch.badkamer_spiegelverwarming
    state: 'on'
  - condition: or
    conditions:
      - condition: state
        entity_id: light.badkamer
        state: 'off'
        for:
          minutes: 5
      - condition: template
        value_template: "{{ (state_attr('sensor.badkamer_luchtvochtigheid_5min', 'variance') | float) < 10 }}"
      - condition: state
        entity_id: switch.badkamer_spiegelverwarming
        state: 'on'
        for:
          hours: 1
action:
  - service: switch.turn_off
    data:
      entity_id: switch.badkamer_spiegelverwarming