---
#
# Turn on the mirror heating when someone is in the shower
#
id: bathroom-mirror_heating
alias: Spiegelverwarming
description: Spiegelverwarming aan bij douchen.

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - sensor.badkamer_luchtvochtigheid_afwijking

action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.badkamer_luchtvochtigheid_afwijking
            above: 20
        sequence:
          - service: switch.turn_on
            data_template:
              entity_id: switch.badkamer_spiegelverwarming
      - conditions:
          - condition: numeric_state
            entity_id: sensor.badkamer_luchtvochtigheid_afwijking
            below: 15
        sequence:
          - service: switch.turn_off
            data_template:
              entity_id: switch.badkamer_spiegelverwarming
