---
#
#
#
id: '1594194765644'
alias: Badkamer Spiegelverwarming Aan
description: ''
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - sensor.badkamer_luchtvochtigheid_5min
      - light.badkamer
      - fan.afzuiging
condition:
  - condition: state
    entity_id: switch.badkamer_spiegelverwarming
    state: 'off'
  - condition: template
    value_template: "{{ (state_attr('sensor.badkamer_luchtvochtigheid_5min', 'variance') | float) > 5 }}"
action:
  - service: switch.turn_on
    data:
      entity_id: 
        - switch.badkamer_spiegelverwarming