---
# 
# Turn on the mirror heating when someone is in the shower
# 
id: 'bathroom-mirror_heating'
alias: Spiegelverwarming
description: 'Spiegelverwarming aan bij douchen'
mode: single
variables:
  average_humidity: >-
    {% 
      set sensors = [
        states('sensor.lily_luchtvochtigheid')|float,
        states('sensor.olivia_luchtvochtigheid')|float
      ]
    %}
    {{ (sensors|sum / sensors|count)|float }}
  delta_humidity: >-
    {{
      states('sensor.slaapkamer_luchtvochtigheid')|float - average_humidity
    }}
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - sensor.lily_luchtvochtigheid
      - sensor.olivia_luchtvochtigheid
      - sensor.slaapkamer_luchtvochtigheid
action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ delta_humidity > 20 }}"
      sequence:
        - service: switch.turn_on
          data_template:
            entity_id: switch.badkamer_spiegelverwarming
    - conditions:
      - condition: template
        value_template: "{{ delta_humidity < 10 }}"
      sequence:
        - service: switch.turn_off
          data_template:
            entity_id: switch.badkamer_spiegelverwarming