---
# 
# Ì've modified my existing Busch-Jaeger light switch with ESPHome and an ESP8266 board
# to make sure I can still toggle the hue light when the switch is in the off position.
# 
id: '1594195813098'
alias: Schakelaar Badkamer Plafond
description: ''
trigger:
- platform: state
  entity_id: binary_sensor.badkamer_plafond_switch
  from: 'on'
  to: 'off'
- platform: state
  entity_id: binary_sensor.badkamer_plafond_switch
  from: 'off'
  to: 'on'
action:
- service: light.toggle
  entity_id: light.badkamer_plafond
  data:
    brightness: 254
    transition: 1