---
#
# https://gist.github.com/niro1987/e7be4b6173d819af3b55f1d4ec114df4
#
id: ikea_dimmer
alias: IKEA Dimmer
description: Control the behaviour of the IKEA Dimmer.

mode: restart

trigger:
  - platform: event
    event_type: zha_event

condition:
  - condition: template
    value_template: '{{ trigger.event.data.device_ieee == "00:0d:6f:ff:fe:a0:54:37" }}'

action:
  - choose:
      # Short-Press the on button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "on" }}'
        sequence:
          - service: light.turn_off
            data_template:
              entity_id: light.eerste_verdieping
              transition: 2
      # Short-Press the off button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "off" }}'
        sequence:
          - service: light.turn_off
            data_template:
              entity_id: light.eerste_verdieping
              transition: 2
      # Long-Press the on button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "move_with_on_off" }}'
        sequence:
          - service: light.turn_off
            data_template:
              entity_id: light.eerste_verdieping
              transition: 2
      # Long-Press the off button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "move" }}'
        sequence:
          - service: light.turn_off
            data_template:
              entity_id: light.eerste_verdieping
              transition: 2
    # Any other event will cancel the repeat loops (i.e. releasing the [on|off] button)
    default: []
