---
# 
# Ì've modified my existing Busch-Jaeger light switch with ESPHome and a Sonoff Mini
# to make sure I can still toggle the hue light when the switch is in the off position.
# 
id: '1594197177829'
alias: Schakelaar Slaapkamer (Aan)
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.slaapkamer_switch
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: binary_sensor.slaapkamer_switch
    from: 'off'
    to: 'on'
condition:
  - condition: state
    entity_id: light.slaapkamer
    state: 'off'
action:
  - service: light.turn_on
    entity_id: light.bed
    data:
      brightness: 50
      hs_color:
      - 38.222
      - 52.941
  - condition: time
    after: '11:00'
    before: '17:00'
  - service: light.turn_on
    entity_id: light.boven_het_bed
    data:
      brightness: 254