---
sensor:
  - name: Afwijking Luchtvochtigheid Badkamer
    unit_of_measurement: "%"
    state: >-
      {% set TARGET = states('sensor.badkamer_luchtvochtigheid')|float %}
      {% set SOURCE = states('sensor.gemiddelde_luchtvochtigheid')|float %}
      {{ (TARGET - SOURCE) | round(2) }}
    attributes:
      target: "{{ states('sensor.badkamer_luchtvochtigheid') }}"
      source: "{{ states('sensor.gemiddelde_luchtvochtigheid') }}"
