---
binary_sensor:
  - name: Droger
    device_class: running
    state: "{{ states('sensor.droger_current_consumption')|float > 2.5 }}"
    availability: "{{ states('sensor.droger_current_consumption')|string != 'None' }}"
    delay_off:
      seconds: 35
    delay_on:
      seconds: 35
