---
binary_sensor:
  - name: Droger
    device_class: running
    state: "{{ states('sensor.droger_current_consumption')|float(0) > 170 }}"
    availability: "{{ states('sensor.droger_current_consumption')|string != 'None' }}"
    delay_off:
      seconds: 60
    delay_on:
      seconds: 0
