---
binary_sensor:
  - name: Droger
    device_class: running
    state: "{{ states('sensor.droger_current_consumption')|float(0) > 50 }}"
    availability: "{{ states('sensor.droger_current_consumption')|string != 'None' }}"
    delay_off:
      minutes: 1
    delay_on:
      seconds: 1
