---
#
#
#
id: 'hallway-light'
alias: Gangverlichting
description: 'Verlichting op de gang aan bij beweging'
mode: restart
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - binary_sensor.gang
action:
  - choose:
    - conditions:
        - condition: state
          entity_id: binary_sensor.gang
          state: 'on'
      sequence:
        - service: light.turn_on
          data_template:
            entity_id: light.gang
    default:
      - service: light.turn_off
        data_template:
          entity_id: light.gang