---
#
#
#
id: '1594460535345'
alias: Gang Automatisch Uit
description: ''
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - light.gang
      - input_number.gang_automatisch_uit
  - platform: state
    entity_id: light.gang
    to: 'on'
    for:
      minutes: '{{ states("input_number.gang_automatisch_uit")|int }}'
condition:
  - condition: state
    entity_id: light.gang
    state: 'on'
  - condition: numeric_state
    entity_id: input_number.gang_automatisch_uit
    above: 0
  - condition: template
    value_template: '{{ ((as_timestamp(now()) - as_timestamp(states.light.gang.last_updated))|int) >= ((states("input_number.gang_automatisch_uit")|float * 60)|int) }}'
action:
  - service: light.turn_off
    entity_id: light.gang