---
#
#
#
id: christmas_lights_off
alias: Christmas Lights Off
description: Turn off Christmas Light at midnight

mode: single
max_exceeded: silent

trigger:
  - platform: sun
    event: sunrise
    offset: "01:00:00"
  - platform: time
    at: "00:00:00"

action:
  - service: switch.turn_off
    data:
      entity_id: switch.ikea_outlet
