---
#
#
#
id: christmas_lights_on
alias: Christmas Lights On
description: Turn on Christmas Light just before sunset.

mode: single
max_exceeded: silent

trigger:
  - platform: sun
    event: sunset
    offset: "-01:00:00"
  - platform: time
    at: "06:00:00"

action:
  - service: switch.turn_on
    data:
      entity_id: switch.ikea_outlet
