---
id: christmas_lights_on
alias: Christmas Lights On
description: Turn on Christmas Light just before sunset

trigger:
  - platform: sun
    event: sunset
    offset: "-01:00:00"
  # - platform: event
  #   event_type: zha_event
  #   event_data:
  #     device_ieee: ""

action:
  - service: switch.turn_on
    data:
      entity_id: switch.ikea_outlet
