---
#
#
#
id: '1594196425601'
alias: Deurbel Notificatie Daan
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.deurbel
    from: 'off'
    to: 'on'
condition:
  - condition: state
    entity_id: person.danielle
    state: home
action:
  - service: notify.mobile_app_j9210
    data:
      title: Deurbel
      message: Ding Dong!
      data:
        group: Deurbel
        tag: Deurbel
        timeout: 60