---
#
#
#
id: '1594196575813'
alias: Deurbel Notificatie Google Home
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.deurbel
    from: 'off'
    to: 'on'
action:
  - service: media_player.play_media
    data:
      entity_id: media_player.woonkamer_mini
      media_content_id: !secret doorbell_sound
      media_content_type: music