---
#
#
#
id: '1594196575813'
alias: Deurbel Notificatie Google Home
description: ''
trigger:
- entity_id: binary_sensor.deurbel
  from: 'off'
  platform: state
  to: 'on'
condition: []
action:
- data:
    media_content_id: https://annanas.diskstation.me:8123/local/deurbel.mp3
    media_content_type: music
  entity_id: media_player.alle_speakers
  service: media_player.play_media