---
#
#
#
id: '1594196323199'
alias: Deurbel Notificatie Niels
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.deurbel
    from: 'off'
    to: 'on'
condition:
  - condition: state
    entity_id: person.niels
    state: home
action:
  - service: notify.mobile_app_nimbus_2000
    data:
      title: Deurbel
      message: Ding! Dong!
      data:
        apns_headers:
          apns-collapse-id: Deurbel
        push:
          thread-id: Deurbel