---
#
# Check for updates in the ESP Home domain and install all.
#
id: system-esphome_update_all
alias: ESPHome Update All
description: Update all ESP Home devices automatically.

mode: single
max_exceeded: silent

trigger:
  - platform: time
    at: "04:00:00"

action:
  - service: update.install
    target:
      entity_id: >-
        {{ states.update | selectattr('state', 'eq', 'on') |
        map(attribute='entity_id') | select('in',
        integration_entities('esphome')) | list }}
