---
#
#
#
id: foscam_intercept
alias: Foscam Intercept
description: >-
  Zet 'foscam_intercept' events om in mqtt berichten zodat deze als
  binary_sensors kunnen worden gebruikt.

mode: single
max_exceeded: silent

trigger:
  - platform: event
    event_type: foscam_intercept

action:
  - service: mqtt.publish
    data_template:
      topic: >-
        foscam_intercept/{{ trigger.event.data.senderTag }}
      payload: >-
        {{ trigger.event.data.msgType }}
