---
#
#
#
id: 'system-foscam_intercept'
alias: Foscam Intercept
description: ''
mode: queued
max: 100
trigger:
  - platform: event
    event_type: foscam_intercept
action:
  - service: notify.file
    data_template:
      message: '{{trigger.event.data}}'