---
#
# This automation turns off the light that was passed through an actionable
# notification on an iOS device. If the users pressed the 'Turn Off'
# button in the notification, the light is turned off. Easy-peasy
#
id: 'system-ios_light_off'
alias: Verlichting Uitschakelen adhv iOS Notificatie
description: 'Licht uit a.u.b.'
mode: queued
trigger:
  - platform: event
    event_type: ios.notification_action_fired  
    event_data:
      actionName: TURN_OFF
      categoryName: light_off
condition:
  - condition: template
    value_template: '{{ states(trigger.event.data.action_data.entity_id) != "unknown" }}'
action:
  - service: light.turn_off
    data_template:
      entity_id: '{{ trigger.event.data.action_data.entity_id }}'