---
#
# This automation triggers the custom integration Samba Backup
# https://github.com/thomasmauerer/hassio-addons/tree/master/samba-backup
#
id: 'system-samba_backup'
alias: Samba Backup
description: 'HomeAssistant Backup'
mode: single
trigger:
  - platform: time
    at: 00:00:00
action:
  - service: hassio.addon_stdin
    data:
      addon: 15d21743_samba_backup
      input: trigger