---
#
#
#
id: '1594195540501'
alias: Samba Backup
description: ''
trigger:
  - platform: time
    at: 00:00:00
action:
  - service: hassio.addon_stdin
    data:
      addon: 15d21743_samba_backup
      input: trigger