---
#
#
#
id: 'system-theme'
alias: Theme
description: ''
mode: single
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: sun.sun
action:
  - choose:
    - conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      sequence:
        - service: frontend.set_theme
          data:
            name: 'clear-dark'
    default:
      - service: frontend.set_theme
        data:
          name: 'clear'