---
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    password: !secret wifi_password
# captive_portal:

web_server:
  port: 80
  auth:
    username: !secret username
    password: !secret password

ota:
  password: !secret password

api:
  # password: !secret password
  reboot_timeout:
    minutes: 10
  encryption:
    key: !secret encryption_key

logger:
  level: DEBUG
