---
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${devicename}
    password: !secret wifi_password
captive_portal:

web_server:
  port: 80
  auth:
    username: !secret username
    password: !secret password

ota:
  password: !secret password

api:
  password: !secret password

logger:
  level: DEBUG
