---
#
# Turn on the mirror heating when someone is in the shower
#
id: badkamer-spiegelverwarming
alias: Badkamer Spiegelverwarming
description: >-
  Zet de spiegelverwarming aan/uit op basis van het verschil in luchtvochtigheid
  tussen de badkamer en de rest van de verdieping.

mode: single
max_exceeded: silent

trigger:
  - platform: numeric_state
    entity_id: sensor.badkamer_luchtvochtigheid_afwijking
    above: 20
    id: "on"
  - platform: numeric_state
    entity_id: sensor.badkamer_luchtvochtigheid_afwijking
    below: 15
    id: "off"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: "on"
        sequence:
          - service: switch.turn_on
            data_template:
              entity_id: switch.badkamer_spiegelverwarming
    default:
      - service: switch.turn_off
        data_template:
          entity_id: switch.badkamer_spiegelverwarming
