---
#
id: meterkast-kerstverlichting
alias: Kerstverlichting
description: Zet de kerstverlichting aan en uit

mode: single
max_exceeded: silent

variables:
  future_state: "on"

trigger:
  - platform: sun
    event: sunset
    id: "on"
  - platform: sun
    event: sunrise
    id: "off"
  - platform: time
    at: "02:00:00"
    id: "off"
  - platform: time
    at: "05:00:00"
    id: "on"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: "off"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.kerstverlichting
    default:
      - service: switch.turn_on
        target:
          entity_id: switch.kerstverlichting
