---
#
# https://www.home-assistant.io/integrations/sensor.rest
#
resource: http://a0d7b954-wireguard
binary_sensor:
  - name: FysioBO1
    value_template: >-
      {{
        (
          now() - timedelta(hours=1)
        ) < value_json.FysioBO1.latest_handshake | as_datetime
      }}
    device_class: connectivity

  - name: FysioBO2
    value_template: >-
      {{
        (
          now() - timedelta(hours=1)
        ) < value_json.FysioBO2.latest_handshake | as_datetime
      }}
    device_class: connectivity

  - name: FysioBO3
    value_template: >-
      {{
        (
          now() - timedelta(hours=1)
        ) < value_json.FysioBO2.latest_handshake | as_datetime
      }}
    device_class: connectivity

sensor:
  - name: FysioBO1 Latest Handshake
    value_template: "{{ value_json.FysioBO1.latest_handshake | as_datetime }}"
    device_class: timestamp
    json_attributes: FysioBO1
  - name: FysioBO1 Received
    value_template: "{{ (value_json.FysioBO1.transfer_rx | float / 1048576) | round(2) }}"
    state_class: total
    unit_of_measurement: MB/s
  - name: FysioBO1 Sent
    value_template: "{{ (value_json.FysioBO1.transfer_tx | float / 1048576) | round(2) }}"
    state_class: total
    unit_of_measurement: MB/s

  - name: FysioBO2 Latest Handshake
    value_template: "{{ value_json.FysioBO2.latest_handshake | as_datetime }}"
    device_class: timestamp
    json_attributes: FysioBO2
  - name: FysioBO2 Received
    value_template: "{{ (value_json.FysioBO2.transfer_rx | float / 1048576) | round(2) }}"
    state_class: total
    unit_of_measurement: MB/s
  - name: FysioBO2 Sent
    value_template: "{{ (value_json.FysioBO2.transfer_tx | float / 1048576) | round(2) }}"
    state_class: total
    unit_of_measurement: MB/s

  - name: FysioBO3 Latest Handshake
    value_template: "{{ value_json.FysioBO3.latest_handshake | as_datetime }}"
    device_class: timestamp
    json_attributes: FysioBO3
  - name: FysioBO3 Received
    value_template: "{{ (value_json.FysioBO3.transfer_rx | float / 1048576) | round(2) }}"
    state_class: total
    unit_of_measurement: MB/s
  - name: FysioBO3 Sent
    value_template: "{{ (value_json.FysioBO3.transfer_tx | float / 1048576) | round(2) }}"
    state_class: total
    unit_of_measurement: MB/s
