---
#
# Ì've modified my existing Busch-Jaeger light switch with ESPHome and a Sonoff Mini
# to make sure I can still toggle the hue light when the switch is in the off position.
#
id: master-bedroom-switch
alias: Schakelaar Slaapkamer
description: Bedient de verlichting

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: binary_sensor.slaapkamer_switch
    from:
      - "on"
      - "off"
    to:
      - "off"
      - "on"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: light.slaapkamer
            state: "off"
        sequence:
          - choose:
              - conditions:
                  - condition: time
                    before: "10:00"
                    after: "21:00"
                sequence:
                  - service: light.turn_on
                    entity_id: light.bed
                    data:
                      brightness: 50
                      hs_color:
                        - 38.222
                        - 52.941
            default:
              - service: light.turn_on
                entity_id: light.slaapkamer
                data:
                  brightness: 254
                  hs_color:
                    - 38.222
                    - 52.941
    default:
      - service: light.turn_off
        entity_id: light.slaapkamer
