---
#
# Ì've modified my existing Busch-Jaeger light switch with ESPHome and a Sonoff Mini
# to make sure I can still toggle the hue light when the switch is in the off position.
#
id: kitch-switch_cupboards
alias: Schakelaar Keukenkastjes
description: Bedient de verlichting.

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: binary_sensor.keukenkastjes_switch
    from:
      - "on"
      - "off"
    to:
      - "off"
      - "on"

action:
  - service: light.toggle
    entity_id: light.keukenkastjes
    data:
      brightness: 254
