---
#
#
#
id: woonkamer-televisie_off
alias: Televisie Auto Off
description: >-
  Schakelt voeding van televisie uit bij inactiviteit

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - media_player.android_tv
    to: "off"
    for:
      hours: 0
      minutes: 5
      seconds: 0

action:
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.android_tv_voeding_switch
