---
#
#
#
id: '1594195432253'
alias: Droger Klaar Uit-Aan
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.droger
    from: 'on'
    to: 'off'
action:
  - service: switch.turn_off
    entity_id:
      - switch.droger
  - delay:
      seconds: 1
  - service: switch.turn_on
    entity_id:
      - switch.droger