---
#
#
#
id: '1594195231939'
alias: Droger Notificatie Niels
description: ''
trigger:
- entity_id: binary_sensor.droger
  from: 'on'
  platform: state
  to: 'off'
condition:
- condition: state
  entity_id: person.niels
  state: home
action:
- data:
    data:
      apns_headers:
        apns-collapse-id: Droger
      push:
        thread-id: Droger
    message: Klaar!
    title: Droger
  service: notify.mobile_app_nimbus_2000