---
#
#
#
id: '1594195231939'
alias: Droger Notificatie Niels
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.droger
    from: 'on'
    to: 'off'
condition:
  - condition: state
    entity_id: person.niels
    state: home
action:
  - service: notify.mobile_app_nimbus_2000
    data:
      title: Droger
      message: Klaar!
      data:
        apns_headers:
          apns-collapse-id: Washok
        push:
          thread-id: Droger