---
#
#
#
id: '1594195113899'
alias: Droger Notificatie Daan
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.droger
    from: 'on'
    to: 'off'
condition:
  - condition: state
    entity_id: person.danielle
    state: home
action:
  - service: notify.mobile_app_j9210
    data:
      title: Droger
      message: Klaar!
      data:
        group: Washok
        tag: Droger
        timeout: 3600