---
#
# I've modified the existing Buva Q-Stream ventilation unit with ESPHome,
# an ESP8266 and a 0-10v PWM-to-Voltage module. The unit has a 0-10v port
# to set the speed and a 15v port to power the ESP and the module.
#
id: '1594194118733'
alias: Badkamer Afzuiging Aan
description: ''
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - sensor.badkamer_luchtvochtigheid_5min
condition:
  - condition: state
    entity_id: fan.afzuiging
    state: 'off'
  - condition: template
    value_template: "{{ (state_attr('sensor.badkamer_luchtvochtigheid_5min', 'variance') | float) > 10 }}"
action:
  - service: fan.turn_on
    data:
      entity_id: 
        - fan.afzuiging
  - service: fan.set_speed
    data:
      entity_id:
        - fan.afzuiging
      speed: high