---
#
#
#
id: '1594197739917'
alias: Wasmachine Notificatie Daan
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.wasmachine
    from: 'on'
    to: 'off'
condition:
  - condition: state
    entity_id: person.danielle
    state: home
action:
  - service: notify.mobile_app_j9210
    data:
      title: Wasmachine
      message: Klaar!
      data:
        group: Washok
        tag: Wasmachine
        timeout: 3600