---
#
#
#
id: '1594197839201'
alias: Wasmachine Notificatie Niels
description: ''
trigger:
- entity_id: binary_sensor.wasmachine
  from: 'on'
  platform: state
  to: 'off'
condition:
- condition: state
  entity_id: person.niels
  state: home
action:
- data:
    data:
      apns_headers:
        apns-collapse-id: Wasmachine
      push:
        thread-id: Wasmachine
    message: Klaar!
    title: Wasmachine
  service: notify.mobile_app_nimbus_2000