---
# 
# Notify anyone who is home that the waching machine is ready.
# 
id: 'attic-wachine_machine'
alias: Wasmachine
description: 'Notificatie wanneer de wasmachine klaar is'
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.wasmachine
    from: 'on'
    to: 'off'
action:
  - choose:
    - conditions:
      - condition: state
        entity_id: person.danielle
        state: 'home'
      sequence:
        - service: notify.mobile_app_j9210
          data:
            title: Wasmachine
            message: Klaar!
            data:
              group: Washok
              tag: Wasmachine
              timeout: 3600
  - choose:
    - conditions:
      - condition: state
        entity_id: person.niels
        state: 'home'
      sequence:
        - service: notify.mobile_app_nimbus_2000
          data:
            title: Wasmachine
            message: Klaar!
            data:
              apns_headers:
                apns-collapse-id: Washok
              push:
                thread-id: Wasmachine