---
#
#
#
id: '1594197739917'
alias: Wasmachine Notificatie Daan
description: ''
trigger:
- entity_id: binary_sensor.wasmachine
  from: 'on'
  platform: state
  to: 'off'
condition:
- condition: state
  entity_id: person.danielle
  state: home
action:
- data:
    data:
      group: Wasmachine
      tag: Wasmachine
      timeout: 600
    message: Klaar!
    title: Wasmachine
  service: notify.mobile_app_j9210