---
substitutions:
  devicename: afzuiging

packages:
  device: !include common/devices/d1_mini.yaml
  base: !include common/default_base.yaml

output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: D1
    frequency: 1000 Hz

fan:
  - platform: speed
    name: 'Afzuiging'
    output: pwm_output
