---
substitutions:
  devicename: badkamer

packages:
  device: !include common/devices/esp32.yaml
  base: !include common/default_base.yaml

output:
  - platform: gpio
    pin: GPIO27
    id: 'output_2'

  - platform: gpio
    pin: GPIO26
    id: 'output_3'

binary_sensor:
  - platform: gpio
    id: 'binary_1'
    name: 'Badkamer Plafond Switch'
    pin:
      number: GPIO16
      mode: INPUT_PULLDOWN
  - platform: gpio
    id: 'binary_2'
    name: 'Badkamer Spiegel Switch'
    pin:
      number: GPIO17
      mode: INPUT_PULLDOWN
    on_state:
      then:
        - light.toggle: light_2

light:
  - platform: binary
    name: 'Badkamer Spiegel'
    output: 'output_2'
    id: 'light_2'

switch:
  - platform: output
    name: 'Badkamer Spiegelverwarming'
    output: 'output_3'
    id: 'switch_1'
    icon: 'mdi:waves'
