---
substitutions:
  devicename: badkamer
  friendlyname: Badkamer

esphome:
  name: ${devicename}
  platform: ESP32
  board: esp32doit-devkit-v1

<<: !include common.txt

output:
  - platform: gpio
    pin: GPIO27
    id: 'output_2'
    
  - platform: gpio
    pin: GPIO26
    id: 'output_3'

binary_sensor:
  - platform: status
    name: '${friendlyname} Status'

  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT_PULLDOWN
    name: '${friendlyname} Plafond Switch'
    id: 'binary_1'

  - platform: gpio
    pin: 
      number: GPIO17
      mode: INPUT_PULLDOWN
    name: '${friendlyname} Spiegel Switch'
    id: 'binary_2'
    on_state:
      then:
        - light.toggle: light_2

light:

  - platform: binary
    name: '${friendlyname} Spiegel'
    output: 'output_2'
    id: 'light_2'

sensor:
  - platform: wifi_signal
    id: 'wifisignal'
    update_interval: 60s
    name: '${friendlyname} Signal'

switch:
  - platform: restart
    name: '${friendlyname} Restart'

  - platform: output
    name: '${friendlyname} Spiegelverwarming'
    output: 'output_3'
    id: 'switch_1'
    icon: 'mdi:waves'