---
substitutions:
  devicename: bbq

packages:
  device: !include common/devices/esp32.yaml
  base: !include common/default_base.yaml

external_components:
  - source: github://bendikwa/esphome-igrill@v1.2

esp32_ble_tracker:

ble_client:
  - mac_address: 70:91:8F:0A:1F:0C
    id: igrill_mini
    on_connect:
      then:
        - binary_sensor.template.publish:
            id: mini_connection_bin
            state: ON
    on_disconnect:
      then:
        - binary_sensor.template.publish:
            id: mini_connection_bin
            state: OFF

sensor:
  - platform: igrill
    ble_client_id: igrill_mini
    update_interval: 5s # default
    send_value_when_unplugged: true # default
    unplugged_probe_value: 0 # default
    battery_level:
      name: "IGrill Mini battery"
    temperature_probe1:
      name: "IGrill Mini temp probe"

binary_sensor:
  - platform: template
    name: "iGrill mini connection status"
    id: mini_connection_bin
    device_class: connectivity
    entity_category: diagnostic
