---
substitutions:
  devicename: bel
  friendlyname: Bel

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

<<: !include common.txt

output:
  - platform: gpio
    id: output_1
    pin: GPIO12

binary_sensor:
  - platform: status
    name: '${friendlyname} Status'

  - platform: gpio
    pin: GPIO4
      # number: GPIO4
      # mode: INPUT_PULLUP
      # inverted: True
    id: binary_1
    name: 'Deurbel'

sensor:
  - platform: wifi_signal
    id: 'wifisignal'
    update_interval: 60s
    name: '${friendlyname} Signal'

switch:
  - platform: restart
    name: '${friendlyname} Restart'

  - platform: output
    name: 'Bel'
    output: 'output_1'
    icon: 'mdi:alarm-bell'