---
substitutions:
  devicename: bel

packages:
  device: !include common/devices/sonoff_mini.yaml
  base: !include common/default_base.yaml

output:
  - platform: gpio
    id: output_1
    pin: GPIO12

binary_sensor:
  - platform: gpio
    id: binary_1
    name: 'Deurbel'
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

switch:
  - platform: output
    name: 'Bel'
    icon: 'mdi:alarm-bell'
    output: 'output_1'
