---
substitutions:
  devicename: eettafel
  static_ip: !secret eettafel_ip

packages:
  device: !include common/devices/sonoff_mini.yaml
  base: !include common/default_base.yaml

binary_sensor:
  - platform: gpio
    id: binary_1
    name: 'Tafel Switch'
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true

  - platform: gpio
    id: binary_2
    name: 'Woonkamer Switch'
    pin:
      number: GPIO16
      # mode: INPUT_PULLUP
      inverted: true
