---
substitutions:
  devicename: esp32_03
  friendlyname: esp32_03

esphome:
  name: ${devicename}
  platform: ESP32
  board: esp32doit-devkit-v1

<<: !include common.txt

status_led:
  pin: GPIO2

binary_sensor:
  - platform: status
    name: '${friendlyname} Status'

sensor:
  - platform: wifi_signal
    id: 'wifisignal'
    update_interval: 60s
    name: '${friendlyname} Signal'

switch:
  - platform: restart
    name: '${friendlyname} Restart'