---
substitutions:
  devicename: gang
  static_ip: !secret gang_ip

packages:
  device: !include common/devices/sonoff_mini.yaml
  base: !include common/default_base.yaml

output:
  - platform: gpio
    id: output_1
    pin: GPIO12

binary_sensor:
  - platform: gpio
    id: binary_1
    name: 'Gang Voorkant'
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
    on_state:
      then:
        - light.toggle: light_1
  - platform: gpio
    id: binary_2
    name: 'Gang Trapkant'
    pin:
      number: GPIO16
      # mode: INPUT_PULLUP
      inverted: true
    on_state:
      then:
        - light.toggle: light_1

light:
  - platform: binary
    id: light_1
    name: 'Gang'
    output: output_1
