---
substitutions:
  devicename: gang
  friendlyname: Gang

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

<<: !include common.txt

status_led:
  pin:
    number: GPIO13
    inverted: true

output:
  - platform: gpio
    id: output_1
    pin: GPIO12

binary_sensor:
  - platform: status
    name: '${friendlyname} Status'

  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    id: binary_1
    name: 'Gang Voorkant'
    on_state:
      then:
        - light.toggle: light_1
    
  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: True
    id: binary_2
    name: 'Gang Trapkant'
    on_state:
      then:
        - light.toggle: light_1

light:
  - platform: binary
    id: light_1
    name: 'Gang'
    output: output_1

sensor:
  - platform: wifi_signal
    id: 'wifisignal'
    update_interval: 60s
    name: '${friendlyname} Signal'

switch:
  - platform: restart
    name: '${friendlyname} Restart'