---
substitutions:
  devicename: keuken

packages:
  device: !include common/devices/sonoff_mini.yaml
  base: !include common/default_base.yaml

output:
  - platform: gpio
    id: output_1
    pin: GPIO12

binary_sensor:
  - platform: gpio
    id: binary_1
    name: 'Keukenplafond Switch'
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
  - platform: gpio
    id: binary_2
    name: 'Keukenkastjes Switch'
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: True

light:
  - platform: binary
    id: light_1
    #name: 'Keukenkastjes'
    output: output_1
