---
substitutions:
  devicename: overloop

packages:
  device: !include common/devices/sonoff_mini.yaml
  base: !include common/default_base.yaml

esphome:
  on_boot:
    then:
      - switch.turn_on: relay_1

switch:
  - platform: gpio
    id: relay_1
    pin: GPIO12

binary_sensor:
  - platform: gpio
    id: binary_1
    name: 'Overloop Switch'
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
