---
substitutions:
  devicename: schuur

packages:
  device: !include common/devices/esp32.yaml
  base: !include common/default_base.yaml

output:
  - platform: gpio
    id: r1
    pin:
      number: 13
      inverted: true
  - platform: gpio
    id: r2
    pin:
      number: 12
      inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: 15
      mode: INPUT_PULLDOWN
      inverted: true
    name: "Werkbank"
    on_press:
      - if:
          condition:
            and:
              - light.is_off: light_20
              - light.is_off: light_100
          then:
            - light.turn_on: light_20
          else:
            - if:
                condition:
                  and:
                    - light.is_on: light_20
                    - light.is_off: light_100
                then:
                  - light.turn_on: light_100
                else:
                  - if:
                      condition:
                        and:
                          - light.is_on: light_20
                          - light.is_on: light_100
                      then:
                        - light.turn_off: light_20
  - platform: gpio
    pin:
      number: 0
    id: "boot"
    on_press:
      then:
        - switch.turn_on: reboot
      
light:
  - platform: binary
    id: light_20
    name: 'Werkbank'
    output: r1
    on_turn_off:
      then:
        - light.turn_off: light_100
  - platform: binary
    id: light_100
    name: 'Werkbank Vel'
    output: r2
    on_turn_on:
      then:
        - light.turn_on: light_20
