---
substitutions:
  devicename: slaapkamer_lily
  static_ip: !secret slaapkamer_lily_ip

packages:
  device: !include common/devices/sonoff_mini.yaml
  base: !include common/default_base.yaml

binary_sensor:
  - platform: gpio
    id: binary_1
    name: 'Slaapkamer Lily Switch'
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
