---
substitutions:
  devicename: slaapkamer

packages:
  device: !include common/devices/sonoff_mini.yaml
  base: !include common/default_base.yaml

binary_sensor:
  - platform: gpio
    id: binary_1
    name: 'Slaapkamer Switch'
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
  - platform: gpio
    id: binary_2
    name: 'Kantoor Switch'
    pin:
      number: GPIO16
      # mode: INPUT_PULLUP
      inverted: True
