---
substitutions:
  devicename: sonoff_mini
  friendlyname: Sonoff Mini

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

<<: !include common.txt

status_led:
  pin:
    number: GPIO13
    inverted: true

binary_sensor:
  - platform: status
    name: '${friendlyname} Status'

sensor:
  - platform: wifi_signal
    id: 'wifisignal'
    update_interval: 60s
    name: '${friendlyname} Signal'

switch:
  - platform: restart
    name: '${friendlyname} Restart'