---
#
#
#
substitutions:
  devicename: wemos

packages:
  device: !include common/devices/d1_mini.yaml
  base: !include common/default_base.yaml

i2c:
  sda: D6
  scl: D7
  

sensor:
  - platform: bme280
    temperature:
      name: "Wemos Temperature"
      id: bme280_temperature
    pressure:
      name: "Wemos Pressure"
      id: bme280_pressure
    humidity:
      name: "Wemos Relative Humidity"
      id: bme280_humidity
    address: 0x76
    update_interval: 60s
  - platform: template
    name: "Wemos Altitude"
    lambda: |-
      const float STANDARD_SEA_LEVEL_PRESSURE = 1013.25; //in hPa, see note
      return ((id(bme280_temperature).state + 273.15) / 0.0065) *
        (powf((STANDARD_SEA_LEVEL_PRESSURE / id(bme280_pressure).state), 0.190234) - 1); // in meter
    update_interval: 60s
    icon: 'mdi:signal'
    unit_of_measurement: 'm'
  - platform: template
    name: "Wemos Absolute Humidity"
    lambda: |-
      const float mw = 18.01534;    // molar mass of water g/mol
      const float r = 8.31447215;   // Universal gas constant J/mol/K
      return (6.112 * powf(2.718281828, (17.67 * id(bme280_temperature).state) /
        (id(bme280_temperature).state + 243.5)) * id(bme280_humidity).state * mw) /
        ((273.15 + id(bme280_temperature).state) * r); // in grams/m^3
    accuracy_decimals: 2
    update_interval: 60s
    icon: 'mdi:water'
    unit_of_measurement: 'g/m³'
  - platform: template
    name: "Wemos Dew Point"
    lambda: |-
      return (243.5*(log(id(bme280_humidity).state/100)+((17.67*id(bme280_temperature).state)/
      (243.5+id(bme280_temperature).state)))/(17.67-log(id(bme280_humidity).state/100)-
      ((17.67*id(bme280_temperature).state)/(243.5+id(bme280_temperature).state))));
    unit_of_measurement: °C
    icon: 'mdi:thermometer-alert'
  
  - platform: ccs811
    eco2:
      name: "Wemos eCO2 Value"
    tvoc:
      name: "Wemos Total Volatile Organic Compound"
    address: 0x5A
    update_interval: 60s
    temperature: bme280_temperature
    humidity: bme280_humidity