---
#
# Toggle the outdoor lights at the front door.
#
id: buitenverlichting-voordeur
alias: Buitenverlichting Voordeur
description: >-
  Zet het licht bij de voordeur aan/uit op basis van de zon.

trigger:
  - platform: sun
    event: sunrise
    id: "off"
  - platform: sun
    event: sunset
    id: "on"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: "off"
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.voordeur
    default:
      - service: light.turn_on
        target:
          entity_id: light.voordeur
