---
#
# Toggle the outdoor lights at the front door.
#
id: buitenverlichting-voordeur_feller
alias: Voordeur feller zetten als de deur open gaat.
description: >-
  Zet het licht bij de voordeur feller als de deur open gaat.

trigger:
  - platform: state
    entity_id: binary_sensor.voordeur
    from: "off"
    to: "on"

condition:
  - condition: state
    entity_id: light.voordeur
    state: "on"

action:
  - variables:
      brightness_now: "{{ state_attr('light.voordeur', 'brightness') }}"
  - service: light.turn_on
    target:
      entity_id: light.voordeur
    data:
      brightness_pct: 100
      transition: 1
  - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.voordeur
        from: "on"
        to: "off"
    timeout:
      minutes: 10
    continue_on_timeout: true
  - service: light.turn_on
    target:
      entity_id: light.voordeur
    data:
      brightness: "{{ brightness_now }}"
      transition: 2
