---
#
#
#
id: meterkast-kerstverlichting_uit
alias: Meterkast Kerstverlichting Uit
description: >-
  Zet de kerstverlichting rond middennacht en bij zonsopkomst uit.

mode: single
max_exceeded: silent

trigger:
  - platform: sun
    event: sunrise
    offset: "01:00:00"
  - platform: time
    at: "00:00:00"

action:
  - service: switch.turn_off
    data:
      entity_id: switch.ikea_outlet
