---
#
#
#
id: 'olivia-camera_notify'
alias: Olivia Camera
description: "Notificatie wanneer Olivia d'r camera beweging of geluid detecteert"
mode: queued
max: 3
trigger:
  - platform: event
    event_type: foscam_intercept
condition:
  - condition: template
    value_template: '{{ trigger.event.data.senderTag == "00626E85E9F6" }}'
action:
# Snapshot
  - service: camera.snapshot
    data_template:
      entity_id: camera.olivia
      filename: '/config/www/snapshots/camera.olivia.now.jpg'
  - delay:
      seconds: 1
# Danielle
  - choose:
  ## Altijd
    - conditions:
        - condition: template
          value_template: >
            {{ states("input_select.danielle_camera_notify") == "Altijd" }}
      sequence:
        - service: notify.mobile_app_j9210
          data_template:
            title: '{{ (trigger.event.data.msg | from_json).title }}'
            message: '{{ (trigger.event.data.msg | from_json).description }}'
            data:
              group: Olivia
              tag: olivia_camera
              image: '/local/snapshots/camera.olivia.now.jpg'
              clickAction: '/lovelace/slaapkamer_olivia'
              timeout: 60
  ## Alleen thuis
    - conditions:
        - condition: template
          value_template: >
            {{ states("input_select.danielle_camera_notify") == "Alleen thuis" }}
        - condition: state
          entity_id: person.danielle
          state: 'home'
      sequence:
        - service: notify.mobile_app_j9210
          data_template:
            title: '{{ (trigger.event.data.msg | from_json).title }}'
            message: '{{ (trigger.event.data.msg | from_json).description }}'
            data:
              group: Olivia
              tag: olivia_camera
              image: '/local/snapshots/camera.olivia.now.jpg'
              clickAction: '/lovelace/slaapkamer_olivia'
              timeout: 60
  ## Alleen donker
    - conditions:
        - condition: template
          value_template: >
            {{ states("input_select.danielle_camera_notify") == "Alleen donker" }}
        - condition: state
          entity_id: binary_sensor.olivia_licht
          state: 'off'
        - condition: state
          entity_id: person.danielle
          state: 'home'
      sequence:
        - service: notify.mobile_app_j9210
          data_template:
            title: '{{ (trigger.event.data.msg | from_json).title }}'
            message: '{{ (trigger.event.data.msg | from_json).description }}'
            data:
              group: Olivia
              tag: olivia_camera
              image: '/local/snapshots/camera.olivia.now.jpg'
              clickAction: '/lovelace/slaapkamer_oliva'
              timeout: 60
# Niels
  - choose:
  ## Altijd
    - conditions:
        - condition: template
          value_template: >
            {{ states("input_select.niels_camera_notify") == "Altijd" }}
      sequence:
        - service: notify.mobile_app_nimbus_2000
          data_template:
            title: '{{ (trigger.event.data.msg | from_json).title }}'
            message: '{{ (trigger.event.data.msg | from_json).description }}'
            data:
              apns_headers:
                apns-collapse-id: Olivia
              push:
                thread-id: olivia_camera
              attachment:
                url: '/local/snapshots/camera.olivia.now.jpg'
              url: '/lovelace/slaapkamer_olivia'
  ## Alleen thuis
    - conditions:
        - condition: template
          value_template: >
            {{ states("input_select.niels_camera_notify") == "Alleen thuis" }}
        - condition: state
          entity_id: person.niels
          state: 'home'
      sequence:
        - service: notify.mobile_app_nimbus_2000
          data_template:
            title: '{{ (trigger.event.data.msg | from_json).title }}'
            message: '{{ (trigger.event.data.msg | from_json).description }}'
            data:
              apns_headers:
                apns-collapse-id: Olivia
              push:
                thread-id: olivia_camera
              attachment:
                url: '/local/snapshots/camera.olivia.now.jpg'
              url: '/lovelace/slaapkamer_olivia'
  ## Alleen donker
    - conditions:
        - condition: template
          value_template: >
            {{ states("input_select.niels_camera_notify") == "Alleen donker" }}
        - condition: state
          entity_id: binary_sensor.olivia_licht
          state: 'off'
        - condition: state
          entity_id: person.niels
          state: 'home'
      sequence:
        - service: notify.mobile_app_nimbus_2000
          data_template:
            title: '{{ (trigger.event.data.msg | from_json).title }}'
            message: '{{ (trigger.event.data.msg | from_json).description }}'
            data:
              apns_headers:
                apns-collapse-id: Olivia
              push:
                thread-id: olivia_camera
              attachment:
                url: '/local/snapshots/camera.olivia.now.jpg'
              url: '/lovelace/slaapkamer_olivia'