---
#
#
#
id: '1594812716463'
alias: Slaapkamer Olivia Overdag Notificatie Niels
description: ''
trigger:
- entity_id: light.olivia_plafond
  for: 00:01:00
  from: 'off'
  platform: state
  to: 'on'
condition:
- condition: state
  entity_id: sun.sun
  state: above_horizon
- after: 09:00
  before: '20:00'
  condition: time
action:
- data_template:
    filename: /config/www/snapshots/current.foscam_olivia.jpg
  entity_id: camera.foscam_olivia
  service: camera.snapshot
- delay: 00:00:01
- data:
    data:
      action_data:
        entity_id: light.olivia_plafond
      apns_headers:
        apns-collapse-id: Olivia
      attachment:
        url: /local/snapshots/current.foscam_olivia.jpg
      push:
        category: light_off
        thread-id: Olivia
      url: /lovelace/slaapkamer_olivia
    message: Olivia d'r licht staat aan.
    title: Olivia
  service: notify.mobile_app_nimbus_2000