---
#
#
#
id: '1594812716463'
alias: Slaapkamer Olivia Overdag Notificatie Niels
description: ''
trigger:
  - platform: state
    entity_id: light.olivia_plafond
    from: 'off'
    to: 'on'
    for:
      minutes: 5
condition:
  - condition: state
    entity_id: sun.sun
    state: above_horizon
  - condition: time
    after: '09:00:00'
    before: '20:00:00'
action:
  - service: camera.snapshot
    data_template:
      entity_id: camera.foscam_olivia
      filename: '/config/www/snapshots/current.foscam_olivia.jpg'
  - delay:
      seconds: 2
  - service: notify.mobile_app_nimbus_2000
    data:
      title: Olivia
      message: Olivia d'r licht staat aan.
      data:
        apns_headers:
          apns-collapse-id: Energie
        push:
          thread-id: olivia_plafond
        attachment:
          url: '/local/snapshots/current.foscam_olivia.jpg'
        url: '/lovelace/slaapkamer_olivia'