---
# 
# Notify anyone who is home when Olivia's lights are turned on during the day.
# 
id: 'olivia-daylight_notify'
alias: Olivia Verlichting Overdag
description: "Notificatie wanneer Olivia d'r licht overdag aan staat"
mode: single
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: 
      - light.olivia_plafond
      - sun.sun
      - binary_sensor.olivia_licht
  - platform: state
    entity_id: light.olivia_plafond
    to: 'on'
    for:
      minutes: 5
condition:
  - condition: state
    entity_id: sun.sun
    state: above_horizon
  - condition: state
    entity_id: binary_sensor.olivia_licht
    state: 'on'
  - condition: state
    entity_id: light.olivia_plafond
    state: 'on'
    for:
      minutes: 5
action:
  - service: camera.snapshot
    data_template:
      entity_id: camera.olivia
      filename: '/config/www/snapshots/camera.olivia.now.jpg'
  - delay:
      seconds: 2
  - choose:
    - conditions:
      - condition: state
        entity_id: person.danielle
        state: 'home'
      sequence:
        - service: notify.mobile_app_j9210
          data:
            title: Olivia
            message: Olivia d'r licht staat aan.
            data:
              group: Energie
              tag: olivia_plafond
              image: '/local/snapshots/camera.olivia.now.jpg'
              clickAction: '/lovelace/slaapkamer_olivia'
              timeout: 600
  - choose:
    - conditions:
      - condition: state
        entity_id: person.niels
        state: 'home'
      sequence:
        - service: notify.mobile_app_nimbus_2000
          data:
            title: Olivia
            message: Olivia d'r licht staat aan.
            data:
              apns_headers:
                apns-collapse-id: Energie
              push:
                thread-id: olivia_plafond
              attachment:
                url: '/local/snapshots/camera.olivia.now.jpg'
              url: '/lovelace/slaapkamer_olivia'
  - delay:
      minutes: 30